### ISSUE TITLE
Improve error handling in RemoteAddressStrategy

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-client-node#65]
If the user has specified an unvalid ip adress the strategy will  throw and forcing unleash to throw. 

Example of exception when user adds IP="l127.0.0.1":
```
Error: invalid CIDR subnet: l127.0.0.1
    at Object.ip.cidrSubnet (/home/node/src/node_modules/ip/lib/ip.js:224:11)
    at RemoteAddressStrategy.isEnabled (/home/node/src/node_modules/unleash-client/lib/strategy/remote-addresss-strategy.js:30:24)
    at /home/node/src/node_modules/unleash-client/lib/client.js:77:33
    at Array.some (<anonymous>)
    at UnleashClient.isEnabled (/home/node/src/node_modules/unleash-client/lib/client.js:71:32)
    at Unleash.isEnabled (/home/node/src/node_modules/unleash-client/lib/unleash.js:115:34)
```

**Comment by ivarconr** [comment]
Closed via https://github.com/Unleash/unleash-client-node/pull/67
